FROM tensorflow/tensorflow:2.1.0-gpu-py3

RUN pip3 install matplotlib seaborn pandas tensorflow-addons tqdm
ADD https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protobuf-python-3.11.4.tar.gz \
    /proto.tar.gz
RUN tar xf proto.tar.gz
WORKDIR /protobuf-3.11.4
RUN ./configure && make -j 6 && make install && ldconfig
