FROM tensorflow/tensorflow:2.1.0-gpu-py3
#FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04
#RUN apt -yqq update && \
#    apt -yqq upgrade && \
#    apt -yqq install libsm6 libxext6 libxrender-dev python3 python3-pip
#
#RUN pip3 install --upgrade pip
#RUN pip3 install opencv-python

RUN pip3 install matplotlib
RUN pip3 install seaborn
#RUN pip3 install numpy
RUN pip3 install pandas
#RUN pip3 install tensorflow-gpu==2.1.0
